return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  opts = {
    preset = "modern",
  },
  config = function(_, opts)
    local wk = require("which-key")
    wk.setup(opts)

    wk.add({
      { "<leader>b", group = "Buffer" },
      { "<leader>bw", desc = "Save" },
      { "<leader>bd", desc = "Delete" },
      { "<leader>bf", desc = "Format", mode = { "n", "v" } },

      { "<leader>c", group = "Code" },
      { "<leader>ca", desc = "Code Action" },
      { "<leader>cR", desc = "Rename File" },

      { "<leader>f", group = "Find" },
      { "<leader>fb", desc = "Buffers" },
      { "<leader>fc", desc = "Config File" },
      { "<leader>ff", desc = "Files" },
      { "<leader>fg", desc = "Git Files" },
      { "<leader>fp", desc = "Projects" },
      { "<leader>fr", desc = "Recent" },

      { "<leader>g", group = "Git" },
      { "<leader>gb", desc = "Branches" },
      { "<leader>gB", desc = "Browse", mode = { "n", "v" } },
      { "<leader>gd", desc = "Diff (Hunks)" },
      { "<leader>gf", desc = "Log File" },
      { "<leader>gg", desc = "Lazygit" },
      { "<leader>gl", desc = "Log" },
      { "<leader>gL", desc = "Log Line" },
      { "<leader>gs", desc = "Status" },
      { "<leader>gS", desc = "Stash" },
      { "<leader>gi", desc = "Issues (open)" },
      { "<leader>gI", desc = "Issues (all)" },
      { "<leader>gp", desc = "PRs (open)" },
      { "<leader>gP", desc = "PRs (all)" },

      { "<leader>h", group = "Hunk" },
      { "<leader>hb", desc = "Blame" },
      { "<leader>hB", desc = "Full Blame" },
      { "<leader>hd", desc = "Diff" },
      { "<leader>hh", desc = "Toggle Blame" },
      { "<leader>hp", desc = "Preview" },
      { "<leader>hr", desc = "Reset" },
      { "<leader>hs", desc = "Stage" },
      { "<leader>hu", desc = "Undo Stage" },

      { "<leader>o", group = "Open" },
      { "<leader>oe", desc = "Explorer (Oil)" },
      { "<leader>ol", desc = "Lazy" },
      { "<leader>om", desc = "Mason" },
      { "<leader>oq", desc = "Diagnostic Quickfix" },

      { "<leader>s", group = "Search" },
      { '<leader>s"', desc = "Registers" },
      { "<leader>s/", desc = "Search History" },
      { "<leader>sa", desc = "Autocmds" },
      { "<leader>sb", desc = "Buffer Lines" },
      { "<leader>sB", desc = "Grep Buffers" },
      { "<leader>sc", desc = "Command History" },
      { "<leader>sC", desc = "Commands" },
      { "<leader>sd", desc = "Diagnostics" },
      { "<leader>sD", desc = "Buffer Diagnostics" },
      { "<leader>sg", desc = "Grep" },
      { "<leader>sh", desc = "Help Pages" },
      { "<leader>sH", desc = "Highlights" },
      { "<leader>si", desc = "Icons" },
      { "<leader>sj", desc = "Jumps" },
      { "<leader>sk", desc = "Keymaps" },
      { "<leader>sl", desc = "Location List" },
      { "<leader>sm", desc = "Marks" },
      { "<leader>sM", desc = "Man Pages" },
      { "<leader>sp", desc = "Plugin Spec" },
      { "<leader>sq", desc = "Quickfix List" },
      { "<leader>sR", desc = "Resume" },
      { "<leader>ss", desc = "LSP Symbols" },
      { "<leader>sS", desc = "Workspace Symbols" },
      { "<leader>su", desc = "Undo History" },
      { "<leader>sw", desc = "Grep Word", mode = { "n", "x" } },

      { "<leader>u", group = "UI" },
      { "<leader>ub", desc = "Toggle Background" },
      { "<leader>uc", desc = "Toggle Conceal" },
      { "<leader>uC", desc = "Colorschemes" },
      { "<leader>ud", desc = "Toggle Diagnostics" },
      { "<leader>uD", desc = "Toggle Dim" },
      { "<leader>ug", desc = "Toggle Indent" },
      { "<leader>uh", desc = "Toggle Inlay Hints" },
      { "<leader>ul", desc = "Toggle Line Numbers" },
      { "<leader>uL", desc = "Toggle Relative Numbers" },
      { "<leader>un", desc = "Dismiss Notifications" },
      { "<leader>us", desc = "Toggle Spelling" },
      { "<leader>uT", desc = "Toggle Treesitter" },
      { "<leader>uw", desc = "Toggle Wrap" },

      { "<leader>w", group = "Window" },
      { "<leader>wa", desc = "Add Workspace Folder" },
      { "<leader>wd", desc = "Delete" },
      { "<leader>w=", desc = "Balance" },
      { "<leader>wh", desc = "Go Left" },
      { "<leader>wj", desc = "Go Down" },
      { "<leader>wk", desc = "Go Up" },
      { "<leader>wl", desc = "Go Right" },
      { "<leader>wo", desc = "Close Others" },
      { "<leader>wr", desc = "Remove Workspace Folder" },
      { "<leader>ws", desc = "Split Below" },
      { "<leader>wv", desc = "Split Right" },
      { "<leader>w_", desc = "Maximize Height" },
      { "<leader>w|", desc = "Maximize Width" },

      { "<leader>.", desc = "Scratch Buffer" },
      { "<leader>,", desc = "Buffers" },
      { "<leader>/", desc = "Grep" },
      { "<leader>:", desc = "Command History" },
      { "<leader>D", desc = "Type Definition" },
      { "<leader>ds", desc = "Show Line Diagnostics" },
      { "<leader>n", desc = "Notification History" },
      { "<leader>N", desc = "Neovim News" },
      { "<leader>rn", desc = "Rename Symbol" },
      { "<leader>S", desc = "Select Scratch" },
      { "<leader>z", desc = "Zen Mode" },
      { "<leader>Z", desc = "Zoom" },
      { "<leader><space>", desc = "Smart Find" },
    })
  end,
}
